import math
x1=float(input("x1 ning qiymatini kiriting:  "))
y1=float(input("y1 ning qiymatini kiriting:  "))
x2=float(input("x2 ning qiymatini kiriting:  "))
y2=float(input("y2 ning qiymatini kiriting:  "))
x3=float(input("x3 ning qiymatini kiriting:  "))
y3=float(input("y3 ning qiymatini kiriting:  "))
a=math.sqrt((x2-x1)*(x2-x1)+(y2-y1)*(y2-y1))
b=math.sqrt((x3-x2)*(x3-x2)+(y3-y2)*(y3-y2))
c=math.sqrt((x3-x1)*(x3-x1)+(y3-y1)*(y3-y1))
p=(a+b+c)
s=math.sqrt(p/2*(p/2-a)*(p/2-b)*(p/2-c))
print(round(p,2))
print(round(s,2))
